### ISSUE TITLE
Chybové hlášky

### ISSUE THREAD

**Issue by VojtaT04** [stany9g/upgraded-waffle#2]
V intranetu jsem odevzdal Meetings a asi po minutě zpracovávání na mě vyskočila chyba "Length cannot be less than zero. (Parameter 'length')" což se mi špatně opravuje, protože chyba asi vyskočila v části kódu, co to testuje a já tedy nevím u čeho přesně je problém. Mohl bych vědět, kde je problém? A šlo by případně udělat detailnější error messages?

![image](https://user-images.githubusercontent.com/59090958/93930789-31870580-fd1e-11ea-9d3b-442d0ca9da8a.png)

**Comment by stany9g** [comment]
@VojtaT04 Ano máš pravdu. Tohle je chyba ještě před tím, než se spustil program s testem. Rád bych udělal detailnější error message, ale osobně žádnou error nepotlačuji a vše propaguji pro vás ven, čili tohle je celá chyba. Večer budu doma a podívám se na to. Klidně sem přilož tvůj Meeting.zip.

**Comment by VojtaT04** [comment]
[Meeting.zip](https://github.com/stany9g/upgraded-waffle/files/5266312/Meeting.zip)
Děkuju

**Comment by VojtaT04** [comment]
Vypadá to, že chyba je na straně serveru ([StackOverflow](https://stackoverflow.com/questions/22033270/getting-length-cannot-be-less-than-zero-parameter-name-length-in-exe-mode)) a problém je s path<i>em</i>.

**Comment by stany9g** [comment]
@VojtaT04 Zkus to teď

**Comment by VojtaT04** [comment]
@stany9g Funguje to, děkuju.
