### ISSUE TITLE
Exceptions - return

### ISSUE THREAD

**Issue by cztrollolcz** [stany9g/upgraded-waffle#3]
Co máme vracet v případech že array má pouze 1, či 0 hodnot, či v případě že ceny pouze klesají? "return 0" to nebere...

**Comment by Michal-Atlas** [comment]
Podle zadání to bere ArgumentException. A prý když ceny klesají stejně musíš udělat právě jeden nákup a prodej.

**Comment by cztrollolcz** [comment]
Tak problém vyřešen - jediný co, tak s klesajícíma cenama je "the best profit" 0....
