### ISSUE TITLE
Too many errors

### ISSUE THREAD

**Issue by HonbraDev** [stany9g/upgraded-waffle#4]
# Attempt 1
I used the macOS Zipping Utility
`CSC : error CS2015: 'C:\inetpub\intranet\UploadedAssignments\temp\Jan.Brabec@mensagymnazium.cz\Stocks\Extracted\__MACOSX\._Stock.cs' is a binary file instead of a text file [C:\inetpub\intranet\UploadedAssignments\temp\Jan.Brabec@mensagymnazium.cz\Stocks\Stocks.csproj]`

# Attempt 2
I used an online ZIP utility (<https://www.files2zip.com/>)
`Killed process due to timeout.`

<hr>

The code is still valid in multiple editors even after extracting.

**Comment by HonbraOfficial** [comment]
When I accidentally used the wrong namespace / class, it threw the correct error after zipping (built in utility). It also once threw a DLL access denied error (I couldn't screenshot it, can't reproduce it)

**Comment by HonbraDev** [comment]
When I accidentally used the wrong namespace / class, it threw the correct error after zipping (built in utility).
It also once threw a DLL access denied error: `Accesss to the path 'Microsoft.TestPlatform.CommunicationUtilities.dll' is denied.`

**Comment by stany9g** [comment]
Attempt 2 is the way to go I assume. `Killed process due to timeout` just means that your solution is slower than 100 seconds which you have for all the tests to pass.
