### ISSUE TITLE
Multiplication int overflow

### ISSUE THREAD

**Issue by RiMiDo420** [stany9g/upgraded-waffle#6]
Dobrý den, neměla by náhodou metoda v zadání multiplication vracet long? Při maximálních inputech 100000 * 100000 * 100000 vyjde 10 ^ 15 a to je více než maximální hodnota integru(2,147,483,647).

**Comment by stany9g** [comment]
Dobrý den, 

dobrá připomínka. Myslel jsem na to a tak velké inputy nedávám, aby jejich součin překročil velikost intu.
