### ISSUE TITLE
Test co by existovat neměl

### ISSUE THREAD

**Issue by cztrollolcz** [stany9g/upgraded-waffle#7]
Ze zadání:
> I give you minimum three integers

Test:
Multiplication.MultiplicationTest.ExceptionWithTwoNumbersTest
Multiplication.MultiplicationTest.ExceptionWithEmptyArrayTest
Multiplication.MultiplicationTest.ExceptionWithOneNumberTest

**Comment by stany9g** [comment]
ups, maybe I lied
https://en.wikipedia.org/wiki/Defensive_programming

You should throw ArgumentException if the input is smaller than 3.
