### ISSUE TITLE
Task 6 - HugeLoremTest

### ISSUE THREAD

**Issue by MartinT1** [stany9g/upgraded-waffle#9]
Nejsem schopnej projít WordCloud.WordCloudTests.HugeLoremTest a nenapadá mě proč. Je pravděpodobné že je to moje chyba, ale nevím v čem by ta chyba mohla být.

Intranet vypíše:
Starting test execution, please wait...
A total of 1 test files matched the specified pattern.
Total tests: 7
     Passed: 6
     Failed: 1
Total time: 5.5132 Seconds
[xUnit.net 00:00:02.23]     WordCloud.WordCloudTests.HugeLoremTest [FAIL]
Test Run Failed.

**Comment by Michal-Atlas** [comment]
I second this

**Comment by stany9g** [comment]
**Text:**
Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Phasellus rhoncus. Nullam rhoncus aliquam metus. Praesent vitae arcu tempor neque lacinia pretium. Etiam ligula pede, sagittis quis, interdum ultricies, scelerisque eu. In dapibus augue non sapien. Fusce consectetuer risus a nunc. Nulla quis diam. Suspendisse sagittis ultrices augue. Duis pulvinar. Maecenas sollicitudin. In enim a arcu imperdiet malesuada. Praesent id justo in neque elementum ultrices.Morbi leo mi, nonummy eget tristique non, rhoncus non leo. In convallis. Phasellus et lorem id felis nonummy placerat.Etiam dui sem, fermentum vitae, sagittis id, malesuada in, quam.Vivamus luctus egestas leo. Maecenas ipsum velit, consectetuer eu lobortis ut, dictum at dui. Cras elementum. Nullam eget nisl.Nulla quis diam.Integer malesuada. Praesent vitae arcu tempor neque lacinia pretium.Aenean placerat. Duis ante orci, molestie vitae vehicula venenatis, tincidunt ac pede. Integer pellentesque quam vel velit.Mauris dolor felis, sagittis at, luctus sed, aliquam non, tellus. In enim a arcu imperdiet malesuada. Proin pede metus, vulputate nec, fermentum fringilla, vehicula vitae, justo. Nullam dapibus fermentum ipsum. Temporibus autem quibusdam et aut officiis debitis aut rerum necessitatibus saepe eveniet ut et voluptates repudiandae sint et molestiae non recusandae.Proin in tellus sit amet nibh dignissim sagittis. Ut tempus purus at lorem.Aliquam ornare wisi eu metus.Etiam bibendum elit eget erat.Praesent vitae arcu tempor neque lacinia pretium.Donec quis nibh at felis congue commodo.Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.Mauris metus. Etiam commodo dui eget wisi.
**Můj výstup programu:**
[expected.txt](https://github.com/stany9g/upgraded-waffle/files/5471212/expected.txt)

**Comment by MartinT1** [comment]
Posílám svůj výstup programu:
[Můj výstup programu.txt](https://github.com/stany9g/upgraded-waffle/files/5471225/Muj.vystup.programu.txt)
**Našel jsem systematickou chybu v expected.txt:** 
Věci jako: **" placerat.Etiam "**
Jsou v expected.txt jako: **"placerat.Etia : 1,"**
To znamená že slova ze kterých se skládají jsou tam méněkrát a "placerat.Etia" By tam nemělo být (nebo by to alspoň mělo být "placerat.Etiam").

Můj program bere " placerat.Etiam " jako "placerat++; Etiam++".

**Comment by VojtaT04** [comment]
Yeah, it is pretty hard to understand what should we count as a word and what should we count as separator. I untderstand it like: 
Separators:
* ' '
* ', '
* '. '
* '! '
* '? '
* ' - '
* '... '
And everything else is a word. Is that correct? @stany9g

**Comment by stany9g** [comment]
Původně jsem to bral, že pokud není za "." mezera (či za jiným separátorem), tak je to spojený a mělo by se to počítat společně. Každopádně teď netuším, proč to usekává poslední písmeno a nemám dneska už čas se na to podívat. Do hodnocení vynechám tento test, čili 6/7 = 100.
